### ISSUE TITLE
Readme links to inaccesible documentation

### ISSUE THREAD

**Issue by robinj** [sky-uk/nemo#13]
The wiki pages linked from the README.md are currently on an internal Sky server which cannot be accessed by the community. Would it be possible to move them over to Github?

**Comment by nowtv-web** [comment]
Hi @robinj you can find it on the github wiki here https://github.com/sky-uk/nemo/wiki/Validation-rules. 
We will update the Readme to point on the right location.

Thanks!

**Comment by robinj** [comment]
Thanks a lot! 

Very entertaining and informative talk at AngularConnect btw
